maker_list = [
    "Automotive CODA",
    "Azure Dynamics",
    "Hyundai",
    "Kia",
    "Chevrolet",
    "Volkswagen",
    "Nissan",
    "BMW",
    "Ford",
    "Genesis",
    "Porsche",
    "Audi",
    "Mercedes-Benz",
    "Tesla",
    "Volvo",
    "smart",
    "MINI",
    "BYD",
    "Jaguar",
    "Cadillac",
    "Rivian",
    "Lucid",
    "Fisker",
    "Polestar",
    "Toyota",
    "Honda",
    "Subaru",
    "Mitsubishi",
    "Mazda",
]

market_class_list = [
    "Small Cars",
    "Coupes",
    "Sports/Sporty Cars",
    "Hatchbacks",
    "Family Sedans",
    "Upscale Sedans",
    "Luxury Sedans",
    "Sport Utility Vehicles",
    "Pickup Trucks",
]

drive_list = [
    "FWD",
    "RWD",
    "4WD",
]